### Get all users
GET http://localhost:3000/users
Accept: application/json


### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jane Smith",
  "email": "jane@example.com"
}

###

### Get user preferences
GET http://localhost:3000/users/cbaac480-8ecc-4185-bfa7-b47ee746ccb7/preferences
Accept: application/json

###

### Create user preferences
POST http://localhost:3000/users/cbaac480-8ecc-4185-bfa7-b47ee746ccb7/preferences
Content-Type: application/json

{
  "languageCode": "en",
  "preferredCommunication": 1,
  "userId": 1
}